app/prueba/page.jsx, components/ContainerOffers.jsx, components/Offer.jsx
created and added Components ContainerOffers and Offers, and then use them in the BuyCourses view.
with applied styles the offers section would look like this:
=> feature: component/ContainerOffers & component/Offer

app/prueba/page.jsx, components/ContainerCreators-.jsx, components/Creator.jsx
Created componentes ContainerCreators and componente Creator
Create the ContainerCreators component, which is a section of the BuyCourses view and also create a Creator component that would represent a card with each course creator. 
With the styles it would look like this:
=> feature: component /Creator & ContainerCreator

app/search/page.jsx, components/Selectors.jsx
create the Selectors component to reduce the Search view and make it more accessible
=> feature: component/Selectors

components/SearchCourses.jsx
in this commit
-Add slice to the component.
=> Feature/Modification Component

app/login/page.jsx
I created the component the Login View, now I would start with the validation issue.
Applying styles it would look like this:
=> feature:component/Login

components/SearchCourses.jsx
In this commit.
Modification, and integration of Pagination simple in SearchCourse Component.
=> Feature/Modification SearchCourses C

app/layout.js, app/login/page.jsx, app/login/validation.js, app/page.js, components/ContainerCards.jsx, store/slice.js
In this task I finished the login validation, I created global access status to know if the user access with his username and password, and also in some pages I removed the nav rendering and the footer.
with styles would look like this: 
VALIDATIONS:
Don't access!:
=> feature: Validation/Login

app/page.js, components/NavBar.jsx
change links of the NavBar, if you are logged in it shows you an image of the user and if you click on it appears some options that the registered user can do.
=> fix:component/NavBar

app/page.js, app/search/page.jsx, components/ContainerCards.jsx, components/ContainerMyCourses.jsx, components/SearchCourses.jsx, public/course.json, store/slice.js
The state of all the courses is divided into those that I have purchased and those that I have not purchased in order to better display the courses in certain components where data is requested.
=> fix:Rendering/containers-Courses

app/layout.js, app/prueba/page.jsx, components/MyContent.jsx, components/MyCourse.jsx
Create the MyContent component, which is rendered on the form to create the courses.
With the styles it would look like this:
=> feature:MyContent/component

app/layout.js, app/login/page.jsx, app/prueba/page.jsx, app/register/page.jsx, components/NavBar.jsx, components/Register.jsx
Create the Register component, later I will put logic to make the Login and the Register the same component with conditionals, add some motions for the visual effects of the component.
=> feature:component/Register

app/checkout/page.jsx, components/Checkout.jsx, components/Summary.jsx, theme/globals.css
Create a Checkout view, which is where payments for course purchases are made. Creating 2 components to represent the same View.
With styles it would look like this:
=> feature:componentView/Checkout

app/login/validateRegister.js, components/Register.jsx, package-lock.json, package.json, store/slice.js
Create fields asking for the POST /user path, to create a new user. 
I still need to see the Login part.
=> feature:route/userRegister

app/login/forgetpassword/[token]/page.jsx, app/login/forgetpassword/page.jsx, store/slice.js
in this commit
-added Forget password component
-added Reset password component
-slice redux for form Component
=> LoginViewComponents

app/create/page.jsx, app/login/page.jsx, app/mycourses/page.jsx, app/prueba/page.jsx, components/Form/Mycontent.jsx, components/Register.jsx
=> fix:update

app/page.js, components/BlogList.jsx, components/CardsBlog.jsx, components/NavBar.jsx
Add some effects with Framer-Motion library
=> fix:added/Framers-Motions

components/BlogList.jsx
in this commit
-Fixxed Styles Component
=> Feature-Component Blog List changed

app/create/page.jsx, app/layout.js, components/Form/AddLesson.jsx, components/Form/CreateCourse.jsx, components/Form/LessonVideo.jsx
Add more functionality when creating curse, modify the components that are rendered in the same create course view and change the functionality of the reducer to manage its global state.
=> fix:funtionCreateCourse

app/search/page.jsx, package-lock.json
=> fix:recovery/View/Search

app/prueba/page.jsx, components/CourseCard.jsx, package.json
In this task I incorporated the Tippy.js library to give more styles to the CardCourses components, later I will continue implementing the styles.
=> feature:AddedStyleTippyJs

app/login/forgetpassword/[token]/page.jsx, app/login/page.jsx, components/NavBar.jsx
in this commit
-Navbar Component actualization
-Login component Fixed
-reset password alerts and validations
=> feature/Modification NavBar Component

app/login/page.jsx, components/ContainerMyCourses.jsx
in this commit
- fixxed style component
=> Feature/Login Componente Fixed

app/completion/page.jsx
in this commit
--view Completion component
=> CompletionComponent
